name: CI
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        firebase-version: ["10.0.1", "10.9.2", "11.15.0"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.12
      - name: Install project
        run: poetry install
      - name: Lint
        run: poetry run poe lint
      - name: Build Docs
        run: poetry run poe docs SPHINXOPTS=-W
      - name: Install Firebase Emulator Suite
        run: npm install -g firebase-tools@${{ matrix.firebase-version }}
      - name: Test
        run: poetry run poe test
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
